import { Leave, User } from "@/interface/interface";

export const users: User[] = [
  {
    id: "1",
    name: "Admin User",
    email: "admin@worksync.com",
    password: "admin123",
    role: "admin",
  },
  {
    id: "2",
    name: "Normal User",
    email: "user@worksync.com",
    password: "user123",
    role: "user",
  },
];


export const mockLeaves: Leave[] = [
  {
    id: "1",
    userId: "u1",
    employeeName: "Alice Johnson",
    leaveType: "Vacation",
    startDate: "2025-10-01",
    endDate: "2026-10-05",
    status: "Approved",
    noOfDays: 5,
    reason: "Family trip to the mountains",
  },
  {
    id: "2",
    userId: "u2",
    employeeName: "Michael Smith",
    leaveType: "Sick",
    startDate: "2025-10-03",
    endDate: "2025-10-04",
    status: "Pending",
    noOfDays: 2,
    reason: "Flu and rest required",
  },
  {
    id: "3",
    userId: "u3",
    employeeName: "Sophia Brown",
    leaveType: "Emergency",
    startDate: "2025-10-06",
    endDate: "2025-10-07",
    status: "Rejected",
    noOfDays: 2,
    reason: "Urgent family emergency",
  },
  {
    id: "4",
    userId: "u4",
    employeeName: "James Williams",
    leaveType: "Vacation",
    startDate: "2025-10-08",
    endDate: "2025-10-12",
    status: "Approved",
    noOfDays: 5,
    reason: "Travel abroad for relaxation",
  },
  {
    id: "5",
    userId: "u5",
    employeeName: "Olivia Davis",
    leaveType: "Sick",
    startDate: "2025-10-10",
    endDate: "2025-10-11",
    status: "Pending",
    noOfDays: 2,
    reason: "Migraine and rest required",
  },
  {
    id: "6",
    userId: "u6",
    employeeName: "William Johnson",
    leaveType: "Vacation",
    startDate: "2025-10-14",
    endDate: "2025-10-20",
    status: "Approved",
    noOfDays: 7,
    reason: "Honeymoon trip",
  },
  {
    id: "7",
    userId: "u7",
    employeeName: "Emma Wilson",
    leaveType: "Emergency",
    startDate: "2025-10-15",
    endDate: "2025-10-15",
    status: "Rejected",
    noOfDays: 1,
    reason: "Unexpected event at home",
  },
  {
    id: "8",
    userId: "u8",
    employeeName: "Daniel Martinez",
    leaveType: "Sick",
    startDate: "2025-10-16",
    endDate: "2025-10-18",
    status: "Approved",
    noOfDays: 3,
    reason: "Recovering from surgery",
  },
  {
    id: "9",
    userId: "u9",
    employeeName: "Ava Anderson",
    leaveType: "Vacation",
    startDate: "2025-10-20",
    endDate: "2025-10-22",
    status: "Pending",
    noOfDays: 3,
    reason: "Short family holiday",
  },
  {
    id: "10",
    userId: "u10",
    employeeName: "Liam Thomas",
    leaveType: "Emergency",
    startDate: "2025-10-23",
    endDate: "2025-10-24",
    status: "Approved",
    noOfDays: 2,
    reason: "Parent’s medical appointment",
  },
];

